on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  test-jdk8:
    name: "rawhide - jdk8"
    runs-on: "ubuntu-latest"
    container: "quay.io/fedora/fedora:37"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 8
        include:
          - jdkconf: JDK 8
            jdkver: "8"
    steps:
      - uses: actions/checkout@v3
      - name: Init
        run: |
          dnf -y install mock wget python3 
      - name: Download Rpms
        run: |
          wget -P "rpms/" "https://packages.adoptium.net/artifactory/rpm/rhel/8/x86_64/Packages/temurin-8-jdk-8.0.372.0.0.7-1.x86_64.rpm" "https://packages.adoptium.net/artifactory/rpm/rhel/8/x86_64/Packages/temurin-8-jre-8.0.372.0.0.7-1.x86_64.rpm"
      - name: Run
        run: ./generic_runner/runner.sh
      - name: Pack results
        if: ${{ always() }}
        shell: msys2 {0}
        run: |
          tar -c "results-jdk${{ matrix.jdkver }}.tar.gz" jtregLogs/ verbose_log_file.log jsf.log
      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          path: "results-jdk${{ matrix.jdkver }}.tar.gz"
        continue-on-error: true
